version: '3.3'

services:
  api:
    image: traefik:1.6
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints: [node.role==manager]
    ports:
      - 80:80       ## HTTP (ACME HTTP Challenge & Redirect)
      - 443:443     ## HTTPS
      - 8080:10443  ## HTTPS (Local area)
      - "${PUBLISH_PORT:?err}:8080" ## Traefik web interface.
    networks:
      - traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- /opt/opm/traefik/log:/traefik-log
      - /opt/opm/traefik/traefik.toml:/traefik.toml
      - /opt/opm/traefik/acme.json:/acme.json
      - /opt/opm/traefik/traefik.key:/traefik-data/traefik.key
      - /opt/opm/traefik/traefik.crt:/traefik-data/traefik.crt

networks:
  traefik-net:
    external: true

