version: 0.1

auth:
  token:
    realm: @FRONTEND_SCHEMA@://@PORTUS_FRONTEND_HOST@/v2/token
    service: @REGISTRY_FRONTEND_HOST@
    issuer: @PORTUS_FRONTEND_HOST@
    rootcertbundle: /certs/portus.crt

http:
  addr: 0.0.0.0:5000
  #tls:
  #  certificate: /certs/portus.crt
  #  key: /certs/portus.key
  #debug:
  #  addr: 0.0.0.0:5001

## ==[[ MinIO setting
#storage:
#  cache:
#    blobdescriptor: inmemory
#  s3:
#    accesskey: @PORTUS_MINIO_ID_SECRET_VALUE@
#    secretkey: @PORTUS_MINIO_PW_SECRET_VALUE@
#    region: ap-northeast-2
#    bucket: @MINIO_BUCKET_NAME@
#    regionendpoint: http://s3:9000
#    encrypt: false
#    secure: false
#    v4auth: true
#    chunksize: 1073741824  # >=5*1024*1024
#    rootdirectory: /
## ]]==

## ==[[ Filesystem setting
storage:
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
## ]]==

notifications:
  endpoints:
    - name: portus
      url: @FRONTEND_SCHEMA@://@PORTUS_FRONTEND_HOST@/v2/webhooks/events
      timeout: 2s
      threshold: 10
      backoff: 1s

