version: '3.3'

services:
  web:
    image: devpi:python37
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-net"
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:${FRONTEND_HOST:?err}"
    secrets:
      - devpi-root-pw
    networks:
      - traefik-net
    environment:
      - "FRONTEND_HOST=${FRONTEND_HOST:?err}"
      - "DEVPI_ROOT_PW_PATH=/run/secrets/devpi-root-pw"
    volumes:
      - "${OPT_DIR:?err}:/data"

networks:
  traefik-net:
    external: true

secrets:
  devpi-root-pw:
    external: true

