debug = false

logLevel = "ERROR"
defaultEntryPoints = ["http", "https"]

[traefikLog]
  filePath = "/traefik-log/traefik.log"

[accessLog]
  filePath = "/traefik-log/access.log"

[entryPoints]
  ## Local area.
  [entryPoints.local-https]
  address = ":10443"
    [entryPoints.local-https.tls]
      [[entryPoints.local-https.tls.certificates]]
      certFile = "/traefik-data/traefik.crt"
      keyFile = "/traefik-data/traefik.key"

  ## Wide area.
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"

  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "@ACME_DOMAIN@"
watch = true
exposedByDefault = false
swarmMode = true

[api]
entryPoint = "traefik"
dashboard = true
debug = false

[acme]
email = "@ACME_EMAIL@"
storage = "acme.json"
entryPoint = "https"
acmeLogging = true
onHostRule = true
  [acme.httpChallenge]
  entryPoint = "http"

[file]
  directory = "/traefik-config/"
  watch = true

