version: '3.3'

services:
  web:
    image: nginx
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-net"
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:${FRONTEND_HOST:?err}"
    networks:
      - traefik-net
    volumes:
      - "${DEFAULT_CONFIG_PATH}:/etc/nginx/conf.d/default.conf"

networks:
  traefik-net:
    external: true

