version: "3.3"

services:
  traefik:
    image: "traefik:v2.10"
    restart: always
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.osom_resolver.acme.tlschallenge=true"
      - "--certificatesresolvers.osom_resolver.acme.email=${ACME_EMAIL:?err}"
      - "--certificatesresolvers.osom_resolver.acme.storage=/letsencrypt/acme.json"
      #-"--log.level=DEBUG"
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"

  watchtower:
    image: "containrrr/watchtower:1.5"
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command:
      - "--label-enable"

  redis:
    image: "redis:7"
    restart: always
    environment:
      - TZ=Asia/Seoul
    command:
      - "redis-server"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  master:
    image: "ghcr.io/osom8979/osom-work:master"
    restart: always
    depends_on:
      - traefik
      - redis
    deploy:
      mode: replicated
      replicas: 2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.osom_master.rule=Host(`${FRONTEND_HOST:?err}`)"
      - "traefik.http.routers.osom_master.entrypoints=websecure"
      - "traefik.http.routers.osom_master.tls.certresolver=osom_resolver"
      - "traefik.http.services.osom_master.loadbalancer.server.port=8080"
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - TZ=Asia/Seoul
    command:
      - "master"
    healthcheck:
      test: ["CMD", "python3", "-m", "osom-work", "health"]
      interval: 10s
      timeout: 5s
      retries: 5
