// Future versions of Hyper may add additional config options,
// which will not automatically be merged into this file.
// See https://hyper.is#cfg for all currently supported options.

module.exports = {
  config: {
    updateChannel: 'stable',
    fontSize: 12,
    fontFamily: 'Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',
    fontWeight: 'normal',
    fontWeightBold: 'bold',
    lineHeight: 1,
    letterSpacing: 0,
    cursorColor: 'rgba(248,28,229,0.8)',
    cursorAccentColor: '#000',
    cursorShape: 'BLOCK',
    cursorBlink: false,
    foregroundColor: '#fff',
    backgroundColor: '#000',
    selectionColor: 'rgba(248,28,229,0.3)',
    borderColor: '#333',
    css: '',
    termCSS: '',
    showHamburgerMenu: '',
    showWindowControls: '',
    padding: '12px 14px',
    colors: {
      black: '#000000',
      red: '#C51E14',
      green: '#1DC121',
      yellow: '#C7C329',
      blue: '#0A2FC4',
      magenta: '#C839C5',
      cyan: '#20C5C6',
      white: '#C7C7C7',
      lightBlack: '#686868',
      lightRed: '#FD6F6B',
      lightGreen: '#67F86F',
      lightYellow: '#FFFA72',
      lightBlue: '#6A76FB',
      lightMagenta: '#FD7CFC',
      lightCyan: '#68FDFE',
      lightWhite: '#FFFFFF',
    },
    shell: '',
    shellArgs: ['--login'],
    env: {},
    bell: 'SOUND',
    copyOnSelect: false,
    defaultSSHApp: true,
    // quickEdit: true,
    // bellSoundURL: 'http://example.com/bell.mp3',
  },

  plugins: [
    "hyper-search",
    "hypercwd",
    "hyperterm-safepaste",
  ],
  localPlugins: [],

  keymaps: {
    // "window:devtools": "ctrl+shift+i",
    // "window:reload": "ctrl+shift+r",
    // "window:reloadFull": "ctrl+shift+f5",
    // "window:preferences": "ctrl+,",
    // "zoom:reset": "ctrl+0",
    // "zoom:in": "ctrl+=",
    // "zoom:out": "ctrl+-",
    // "window:new": "ctrl+shift+n",
    // "window:minimize": "ctrl+shift+m",
    // "window:zoom": "ctrl+shift+alt+m",
    // "window:toggleFullScreen": "f11",
    // "window:close": "ctrl+shift+q",
    // "tab:new": "ctrl+shift+t",
    // "tab:next": [
    //   "ctrl+shift+]",
    //   "ctrl+shift+right",
    //   "ctrl+alt+right",
    //   "ctrl+tab"
    // ],
    // "tab:prev": [
    //   "ctrl+shift+[",
    //   "ctrl+shift+left",
    //   "ctrl+alt+left",
    //   "ctrl+shift+tab"
    // ],
    // "tab:jump:prefix": "ctrl",
    // "pane:next": "ctrl+pageup",
    // "pane:prev": "ctrl+pagedown",
    "pane:splitVertical": "ctrl+shift+d",
    "pane:splitHorizontal": "ctrl+shift+e",
    // "pane:close": "ctrl+shift+w",
    // "editor:undo": "ctrl+shift+z",
    // "editor:redo": "ctrl+shift+y",
    // "editor:cut": "ctrl+shift+x",
    // "editor:copy": "ctrl+shift+c",
    // "editor:paste": "ctrl+shift+v",
    // "editor:selectAll": "ctrl+shift+a",
    // "editor:movePreviousWord": "ctrl+left",
    // "editor:moveNextWord": "ctrl+right",
    // "editor:moveBeginningLine": "home",
    // "editor:moveEndLine": "end",
    // "editor:deletePreviousWord": "ctrl+backspace",
    // "editor:deleteNextWord": "ctrl+del",
    // "editor:deleteBeginningLine": "ctrl+home",
    // "editor:deleteEndLine": "ctrl+end",
    // "editor:clearBuffer": "ctrl+shift+k",
    // Linux - no emojis
    // "editor:break": "ctrl+c",
    // "plugins:update": "ctrl+shift+u"
  },
};

