" Vim setting.

scriptencoding utf-8

" Global directory.
let g:opm_vim_script_dir = expand('<sfile>:p:h')
let &runtimepath .= ',' . g:opm_vim_script_dir

function! s:GetOpyPythonPath(home, prefix, name, version)
    return a:home    . '/.pyenv/versions/' .
         \ a:prefix  . '-' .
         \ a:name    . '-' .
         \ a:version . '/bin/python'
endfunction

let s:home_dir = $HOME
let s:user_name = $USER
let s:opy_prefix = 'opy'

function! s:GetOpyPythonPath2(version)
    return s:GetOpyPythonPath(s:home_dir, s:opy_prefix, s:user_name, a:version)
endfunction

let s:opy2_version = '2.7.15'
let s:opy3_version = '3.6.1'

let s:opy2_python_path = s:GetOpyPythonPath2(s:opy2_version)
let s:opy3_python_path = s:GetOpyPythonPath2(s:opy3_version)

if executable(s:opy2_python_path)
    let g:python_host_prog = s:opy2_python_path
endif
if executable(s:opy3_python_path)
    let g:python3_host_prog = s:opy3_python_path
endif

"let g:loaded_python_provider = 1
"let g:loaded_python3_provider = 1

" Vim setting files.
execute 'source ' . g:opm_vim_script_dir . '/vim/plugin.vim'
execute 'source ' . g:opm_vim_script_dir . '/vim/config.vim'
execute 'source ' . g:opm_vim_script_dir . '/vim/keymap.vim'
execute 'source ' . g:opm_vim_script_dir . '/vim/macro.vim'

