version: '3.3'

services:
  db:
    image: mongo:3.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - net
    volumes:
      - raw_db:/data/db
    command: ["--smallfiles"]

  web:
    image: rocket.chat
    depends_on:
      - db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.port=3000"
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.rule=Host:${FRONTEND_HOST:?err}"
    networks:
      - traefik-net
      - net
    environment:
      - "ROOT_URL=http://${FRONTEND_HOST:?err}"

volumes:
  raw_db:

networks:
  traefik-net:
    external: true
  net:
    driver: overlay

