debug = false

logLevel = "ERROR"
defaultEntryPoints = ["https"]

#[traefikLog]
#  filePath = "/traefik-log/traefik.log"
#
#[accessLog]
#  filePath = "/traefik-log/access.log"

[entryPoints]
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/traefik-data/traefik.crt"
      keyFile = "/traefik-data/traefik.key"

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "@LOCAL_DOMAIN@"
watch = true
exposedByDefault = false
swarmMode = true

[api]
entryPoint = "traefik"
dashboard = true
debug = false

