version: '3.3'

services:
  web:
    image: portainer/portainer
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints: [node.role==manager]
    ports:
      - "${PUBLISH_PORT:?err}:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data

volumes:
  data:

