version: '3.3'

services:
  db:
    image: mariadb
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    networks:
      - net
    secrets:
      - mediawiki-wikiuser-pw
    environment:
      - "MYSQL_DATABASE=my_wiki"
      - "MYSQL_USER=wikiuser"
      - "MYSQL_PASSWORD_FILE=/run/secrets/mediawiki-wikiuser-pw"
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"
    volumes:
      - raw_db:/var/lib/mysql

  web:
    image: mediawiki
    depends_on:
      - db
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      labels:
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.rule=Host:${FRONTEND_HOST:?err}"
    networks:
      - traefik-net
      - net
    volumes:
      - images:/var/www/html/images
      - /opt/mediawiki/backup:/backup
      - /opt/mediawiki/mediawiki-phpconfig.ini:/usr/local/etc/php/conf.d/mediawiki-phpconfig.ini
      - /opt/mediawiki/SimpleMathJax:/var/www/html/extensions/SimpleMathJax
      - /opt/mediawiki/osom-logo.png:/var/www/html/resources/assets/wiki.png
      # After initial setup, download LocalSettings.php to the same directory as
      # this yaml and uncomment the following line and use compose to restart
      # the mediawiki service
      #- /opt/mediawiki/LocalSettings.php:/var/www/html/LocalSettings.php

volumes:
  images:
  raw_db:

secrets:
  mediawiki-wikiuser-pw:
    external: true

networks:
  traefik-net:
    external: true
  net:
    driver: overlay

