version: '3.3'

services:
  api:
    image: onlyoffice/documentserver
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-net"
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:${FRONTEND_HOST:?err}"
    stdin_open: true
    networks:
      - traefik-net
    volumes:
      - logs:/var/log/onlyoffice
      - data:/var/www/onlyoffice/Data
      - /opt/opm/onlyoffice/default.json:/etc/onlyoffice/documentserver/default.json

volumes:
  logs:
  data:

networks:
  traefik-net:
    external: true

