version: '3.3'

services:
  web:
    image: rawmind/cloud9-sdk:0.3.0-2
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    ports:
      - "${PUBLISH_PORT:?err}:8080"
    volumes:
      - "${DOCKER_PATH:?err}:/bin/docker"
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/c9/workspace:/workspace
    command: ["--listen", "0.0.0.0",
              "--port", "8080",
              "-w", "/workspace",
              "--collab",
              "--auth", "${CLOUD9_USER?err}:${CLOUD9_PASS:?err}"]

