version: "3.3"

services:
  web:
    image: gitlab/gitlab-ce:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      labels:
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.rule=Host:${FRONTEND_HOST:?err}"
    networks:
      - traefik-net
      - mailhog-net
    volumes:
      - /opt/gitlab/gitlab.rb:/gitlab.rb
      - data:/var/opt/gitlab
      - logs:/var/log/gitlab
      - config:/etc/gitlab
    environment:
      - "GITLAB_OMNIBUS_CONFIG=from_file('/gitlab.rb')"

  runner:
    image: gitlab/gitlab-runner
    deploy:
      mode: replicated
      replicas: 4
      #placement:
      #  constraints: [node.role == worker]

volumes:
  data:
  logs:
  config:

networks:
  traefik-net:
    external: true
  mailhog-net:
    external: true

