version: '3.3'

services:
  api:
    image: mailhog/mailhog
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    ports:
      #- 1025:1025 ## Default SMTP port.
      - 10002:8025 ## MailHog web interface.
    networks:
      - mailhog-net

networks:
  mailhog-net:
    external: true

