version: '3.3'

services:
  db:
    image: mattermost/mattermost-prod-db
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    networks:
      - net
    secrets:
      - mattermost-mmuser-pw
    environment:
      - "POSTGRES_DB=mattermost"
      - "POSTGRES_USER=mmuser"
      - "POSTGRES_PASSWORD_FILE=/run/secrets/mattermost-mmuser-pw"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - raw_db:/var/lib/postgresql/data

  web:
    image: mattermost/mattermost-prod-app
    depends_on:
      - db
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      labels:
        - "traefik.enable=true"
        - "traefik.port=8000"
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.rule=Host:${FRONTEND_HOST:?err}"
        # generate a TLS cert for this domain
        - "traefik.entrypoints=https"
        - "traefik.frontend.passHostHeader=true"
        # loadbalancer
        - "traefik.backend.loadbalancer.sticky=true"
        - "traefik.backend.loadbalancer.swarm=true"
    networks:
      - traefik-net
      - net
    secrets:
      - mattermost-mmuser-pw
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - config:/mattermost/config
      - data:/mattermost/data
      - logs:/mattermost/logs
      - /opt/mattermost/mattermost-entrypoint.sh:/entrypoint.sh
    environment:
      - "DB_HOST=${STACK_NAME:?err}_db"
      - "DB_PORT_NUMBER=5432"
      - "MM_USERNAME=mmuser"
      - "MM_PASSWORD_FILE=/run/secrets/mattermost-mmuser-pw"
      - "MM_DBNAME=mattermost"
      # pass the edition to be used, default is enterprise
      # setting this env var will make the app use the team edition
      - "edition=team"
      # in case your config is not in default location
      # - MM_CONFIG=/mattermost/config/config.json deploy:

volumes:
  config:
  data:
  logs:
  raw_db:

secrets:
  mattermost-mmuser-pw:
    external: true

networks:
  traefik-net:
    external: true
  net:
    driver: overlay

