version: '3.3'

services:
  db:
    image: mariadb
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - net
    secrets:
      - mediawiki-wikiuser-pw
    environment:
      - "MYSQL_DATABASE=my_wiki"
      - "MYSQL_USER=wikiuser"
      - "MYSQL_PASSWORD_FILE=/run/secrets/mediawiki-wikiuser-pw"
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"

  web:
    image: mediawiki
    depends_on:
      - db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.rule=Host:${FRONTEND_HOST:?err}"
    networks:
      - traefik-net
      - net
    volumes:
      - /opt/mediawiki/backup:/backup
      - images:/var/www/html/images

volumes:
  images:

secrets:
  mediawiki-wikiuser-pw:
    external: true

networks:
  traefik-net:
    external: true
  net:
    driver: overlay

