version: '3.3'

services:
  db:
    image: mariadb
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    networks:
      - net
    secrets:
      - nextcloud-clouduser-pw
    environment:
      - "MYSQL_DATABASE=nextcloud"
      - "MYSQL_USER=clouduser"
      - "MYSQL_PASSWORD_FILE=/run/secrets/nextcloud-clouduser-pw"
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"
    volumes:
      - raw_db:/var/lib/mysql

  web:
    image: nextcloud
    depends_on:
      - db
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      labels:
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.rule=Host:${FRONTEND_HOST:?err}"
    networks:
      - traefik-net
      - net
    volumes:
      - data:/var/www/html

volumes:
  data:
  raw_db:

secrets:
  nextcloud-clouduser-pw:
    external: true

networks:
  traefik-net:
    external: true
  net:
    driver: overlay

