version: '3.3'

services:
  api:
    image: sonatype/nexus3
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    ports:
      - 10003:8081
      - 10004:8082
    volumes:
      - data:/nexus-data

volumes:
  data:

