version: '3.3'

services:
  api:
    image: onlyoffice/documentserver
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    networks:
      - net
    volumes:
      - logs:/var/log/onlyoffice
      - data:/var/www/onlyoffice/Data

  web:
    image: nginx
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    networks:
      - onlyoffice-net
      - net
    volumes:
      - /opt/onlyoffice/certs/onlyoffice.key:/etc/nginx/conf.d/key.pem
      - /opt/onlyoffice/certs/onlyoffice.crt:/etc/nginx/conf.d/cert.pem
      - /opt/onlyoffice/proxy_ssl.conf:/etc/nginx/conf.d/proxy_ssl.conf

volumes:
  logs:
  data:

networks:
  onlyoffice-net:
    external: true
  net:
    driver: overlay

