version: '3.3'

services:
  api:
    image: onlyoffice/documentserver
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    stdin_open: true
    networks:
      - onlyoffice-net
    volumes:
      - logs:/var/log/onlyoffice
      - /opt/onlyoffice:/var/www/onlyoffice/Data

volumes:
  logs:

networks:
  onlyoffice-net:
    external: true

