version: '3.3'

services:
  web:
    image: portainer/portainer
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role==manager]
      labels:
        - "traefik.enable=true"
        - "traefik.port=9000"
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.rule=Host:${FRONTEND_HOST:?err}"
    networks:
      - traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  traefik-net:
    external: true

