debug = false

logLevel = "ERROR"
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "@ACME_DOMAIN@"
watch = true
exposedByDefault = false
swarmMode = true

[api]
entryPoint = "traefik"
dashboard = true
debug = false

[acme]
email = "@ACME_EMAIL@"
storage = "acme.json"
entryPoint = "https"
acmeLogging = true
onHostRule = true
  [acme.httpChallenge]
  entryPoint = "http"


