version: '3.3'

services:
  api:
    image: traefik:1.6
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role==manager]
    ports:
      - 80:80     ## HTTP (ACME HTTP Challenge & Redirect)
      - 443:443   ## HTTPS
      - 8080:8080 ## Traefik web interface.
    networks:
      - traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/traefik/traefik.toml:/traefik.toml
      - /opt/traefik/acme.json:/acme.json

networks:
  traefik-net:
    external: true

