debug = false

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "@DOMAIN_NAME@"
watch = true
exposedByDefault = false

[acme]
email = "@EMAIL@"
storage = "acme.json"
entryPoint = "https"
acmeLogging = true
onHostRule = true

[[acme.domains]]
  main = "*.@DOMAIN_NAME@"

[acme.httpChallenge]
  entryPoint = "http"

