#!/usr/bin/env bash

if [[ -z $TPARTY_PREFIX ]]; then
    TPARTY_PREFIX=/usr/local/tparty
fi

export TPARTY_PREFIX

TPARTY_BIN=$TPARTY_PREFIX/bin
TPARTY_INC=$TPARTY_PREFIX/include
TPARTY_LIB=$TPARTY_PREFIX/lib

## GCC setting.
export PATH="$TPARTY_BIN:$PATH"
export CPATH="$TPARTY_INC:$CPATH"
export LIBRARY_PATH="$TPARTY_LIB:$LIBRARY_PATH"
export DYLD_FALLBACK_LIBRARY_PATH="$TPARTY_LIB:$DYLD_FALLBACK_LIBRARY_PATH"

#export LD_LIBRARY_PATH="$TPARTY_LIB:$LD_LIBRARY_PATH"
#export DYLD_LIBRARY_PATH="$TPARTY_LIB:$DYLD_LIBRARY_PATH"

## Pkg-config setting.
export PKG_CONFIG_PATH="$TPARTY_LIB/pkgconfig:$PKG_CONFIG_PATH"

echo "[Tparty Environment]"
echo " CFLAGS=\"-I${TPARTY_INC}\""
echo " LDFLAGS=\"-L${TPARTY_LIB}\""

