// Future versions of Hyper may add additional config options,
// which will not automatically be merged into this file.
// See https://hyper.is#cfg for all currently supported options.

module.exports = {
  config: {
    updateChannel: 'stable',
    fontSize: 12,
    fontFamily: 'Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',
    fontWeight: 'normal',
    fontWeightBold: 'bold',
    lineHeight: 1,
    letterSpacing: 0,
    cursorColor: 'rgba(248,28,229,0.8)',
    cursorAccentColor: '#000',
    cursorShape: 'BLOCK',
    cursorBlink: false,
    foregroundColor: '#fff',
    backgroundColor: '#000',
    selectionColor: 'rgba(248,28,229,0.3)',
    borderColor: '#333',
    css: '',
    termCSS: '',
    showHamburgerMenu: '',
    showWindowControls: '',
    padding: '12px 14px',
    colors: {
      black: '#000000',
      red: '#C51E14',
      green: '#1DC121',
      yellow: '#C7C329',
      blue: '#0A2FC4',
      magenta: '#C839C5',
      cyan: '#20C5C6',
      white: '#C7C7C7',
      lightBlack: '#686868',
      lightRed: '#FD6F6B',
      lightGreen: '#67F86F',
      lightYellow: '#FFFA72',
      lightBlue: '#6A76FB',
      lightMagenta: '#FD7CFC',
      lightCyan: '#68FDFE',
      lightWhite: '#FFFFFF',
    },
    shell: '',
    shellArgs: ['--login'],
    env: {},
    bell: 'SOUND',
    copyOnSelect: false,
    defaultSSHApp: true,
    // quickEdit: true,
    // bellSoundURL: 'http://example.com/bell.mp3',
  },

  plugins: [
    "hyper-search",
    "hypercwd",
    "hyperterm-safepaste",
  ],
  localPlugins: [],

  keymaps: {
    // "window:devtools": "command+alt+i",
    // "window:reload": "command+shift+r",
    // "window:reloadFull": "command+shift+f5",
    // "window:preferences": "command+,",
    // "zoom:reset": "command+0",
    // "zoom:in": "command+plus",
    // "zoom:out": "command+-",
    // "window:new": "command+n",
    // "window:minimize": "command+m",
    // "window:zoom": "ctrl+alt+command+m",
    // "window:toggleFullScreen": "command+ctrl+f",
    // "window:close": "command+shift+w",
    // "tab:new": "command+t",
    // "tab:next": [
    //   "command+shift+]",
    //   "command+shift+right",
    //   "command+alt+right",
    //   "ctrl+tab"
    // ],
    // "tab:prev": [
    //   "command+shift+[",
    //   "command+shift+left",
    //   "command+alt+left",
    //   "ctrl+shift+tab"
    // ],
    // "tab:jump:prefix": "command",
    // "pane:next": "command+]",
    // "pane:prev": "command+[",
    "pane:splitVertical": "ctrl+shift+d",
    "pane:splitHorizontal": "ctrl+shift+e",
    // "pane:close": "command+w",
    "editor:undo": "command+z",
    "editor:redo": "command+shift+z",
    // "editor:cut": "command+x",
    // "editor:copy": "command+c",
    // "editor:paste": "command+v",
    // "editor:selectAll": "command+a",
    // "editor:movePreviousWord": "alt+left",
    // "editor:moveNextWord": "alt+right",
    // "editor:moveBeginningLine": "command+left",
    // "editor:moveEndLine": "command+right",
    // "editor:deletePreviousWord": "alt+backspace",
    // "editor:deleteNextWord": "alt+delete",
    // "editor:deleteBeginningLine": "command+backspace",
    // "editor:deleteEndLine": "command+delete",
    // "editor:clearBuffer": "command+k",
    // "editor:emojis": "command+ctrl+space",
    // "editor:break": "ctrl+c",
    // "plugins:update": "command+shift+u"
  },
};

